version: "3.8"

services:
  front:
    build: 
      context: ./src/front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/front:/app/src/front

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  php:
    build:
      context: ./src/back
      dockerfile: Dockerfile 
    volumes: 
      - "./src/back:/usr/share/nginx/html"

  nginx:
    image: nginx:latest
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./src/back:/usr/share/nginx/html"
    depends_on:
      - php
    ports:
      - "80:80"